Continue running tests even if previous unit tests failed
opencv/ci-gha-workflow pull request #9
Opened 2022-06-02 12:15 UTC by asenyaev

This PR fixes https://github.com/opencv/ci-gha-workflow/issues/7 for current workflows.

2022-06-04 14:02 UTC, fengyuentau requested changes
Can you confirm whether this condition `if: ${{ always() && steps.build-opencv-contrib.outcome == 'success' }}` can stop a step if build is failed or the workflow is cancelled?

2022-06-06 11:52 UTC, asenyaev commented on .github/workflows/OCV-Contrib-PR-3.4-ARM64.yaml
> +      if: ${{ success() && steps.build-opencv-contrib.outcome == 'success' }}
Agree, added an id for java test and changed the if condition.

2022-06-06 11:52 UTC, asenyaev commented
> Can you confirm whether this condition `if: ${{ always() && steps.build-opencv-contrib.outcome == 'success' }}` can stop a step if build is failed or the workflow is cancelled?

Yes, the example job is [here](https://github.com/opencv/ci-gha-workflow/runs/6708090236?check_suite_focus=true).

2022-06-07 02:11 UTC, fengyuentau approved these changes
👍

2022-06-08 09:40 UTC, merged